spring:
  profiles:
    include: dev

zuul:
  routes:
    actor-registry.url: http://localhost:5100

  #Ribbon is auto integrated with Zuul and for this exercise we are not using that.
ribbon:
  eureka:
    enabled: false

server:
  port: 80