variables:
    GC_SERVICE_KEY: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAibWFlc3Rlcm1pZGRsZXdhcmUiLAogICJwcml2YXRlX2tleV9pZCI6ICIwMGVkZjg2YWFiMWQ3ZDZjNTZjNmVlODQyMmVmMDc0OTZiMmFhMzhjIiwKICAicHJpdmF0ZV9rZXkiOiAiLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tXG5NSUlFdlFJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLY3dnZ1NqQWdFQUFvSUJBUURBeVpyc0kzYlcxQWp5XG51eHJ5NjdKa0Nmc1ZidFJLdGF3WUgvMzBjVDQvZVVESGJVYlFxT2VnT0VlNzdHajZOQjgzT2Y5SWdOeTdqZjFqXG5MSnJPMVdMdi9SOHo5VS9pWGEzY3d3WFo2Snd3dldOMVVtS3JzZ1pLQ1hJVmF6QWJoWmxYWEY2VjBLMHBNZXd2XG51c3lHUW9EWjZBeDZkRk9Cdkc5UHNKZ2FuanZodFFIMVBGRncwK0gya1JFZFpIU28xZkZIdUI3VjNzZkNDVzV1XG5HS1JvS1NkdVFVVDVzYXlUbG9lWmNjVC9wbklRNkFUQi9hdnJ5VDI4S3RuN0dscWVxK0h1dTJPc3RMOTFpbEZqXG5mNWpNZ2lUZElsWlVNZ0RSSThjL2Q5SjMrMnMyRUVUTE96UjA2ckoyUFhEQk1ldVFZNWRlTXdENkVaWXNoSWZCXG5WRGd1NStDaEFnTUJBQUVDZ2dFQUhoWDRSdHk3K1llcWc5TGVRRVczRjdTVkNnRzdRSk44Y1dGZ3ZPcUZSOXVRXG4xKzUrVENibnl0R3RwQzZmTFZpLy9GcmhNM3ZrdHFKUWhrOGFNNmdLWWlCeTQ2Vm5XNUM2QnNjcW5SaVhjMlhDXG41VGEvcmtMQWg0SlUydkhZMXBxeFZQaFZ6SFI5NlgxZ2VneGhTWnlNUmpWWDZTNUpMK2hyeUpockRGQmdVUGNzXG5vNXc5L3IvYy9OVWRsYnZGcnZoZm1GT1lXUlExcnVadStZd2tGQXJ5SmFjWmlXcTlDams4V2lUWUVseTRuZlZIXG5UeTFQaHA5TGs0OXl3SnpBK1VKUWhzRFo5enZldXNBOWxaVzVZUTFieDFGUjRVV1FYWS94aTZVNWRuTHRLcFFUXG5jSmU3cnZia2hJZGRjOG9OSHc2SUJDSTdxYVViZDU0SWI5SkdQQUxuYVFLQmdRRGtEam5mM28vNlVkM3l4b21BXG5mampsTUpoZksyZFF1V1Q4czFpazJIMDFSOWg5WTFGclhnc2JhU054U3NkLzdiZzFadFNWZ0FyejdnM3hDY3QxXG5aNnBiczFRSUJldTRBQmcrYXBFSkE4ajFOK2ROaFl6NHROTWthSis4NXpOTk9qKy9FNTJDQnJCNDE3Q0grK2NVXG52WElCYmhJSWg4SGxsaGNJRUFNNWY5b3V6UUtCZ1FEWWFSSS9iM09JTlorL051VVVxWjM0d3dFTFdwcndjUlJWXG5mdGxXck90VXZqQTdHbDRrQmtSNzc1alpuV1c4WkhHcjA0cTlQUnAxVmoyeEwzOFc3TnUxWTA0MWx5VXhTMWhQXG5MTnpRM241MytyVWRzV0tsci9NeHY3dnZSdWdrRGE0bnFTVGVHcHhvYW5vdjExQnl2OGRyZnB2bWtMUkNmMk1ZXG41Vk1ZbFZHUkpRS0JnRXllUXU5bGxMV2l2NUNMQnpNMk5PTTdPbFh1L1J6dnpHL2h5VXhJdDNncEZTQzdOMlY5XG5DUHBDam5mSGlkTC9DTDVZTjkrcVR3TzQzTkk0V2pTdGlWeVptUWZCQlhxaC9ZTXF4bU5pOUNiK2l5Vk9VeGhUXG5tQVJKYWpGSzg3OWtiSHBEbXMxT2RnZURYM213TmVpUDVUZDV4WEU4T3ZacFFIK2k4WkpsMCtXWkFvR0FGVnlCXG52WnM5dHpNNzJuOExxN2QyYldpcVFMbW4wNVlGNE02Tm0zMmtHUkJRNkhTWTJFdDZGUlc0YTdxYW9UYjA5WFlEXG5HdHplTUxqYmpCTFpJNlVycHNMdnBHQ1Ava2FtcCtJUXhkbEFlSTFadFYyZUZDYkRCYVVjWXVrSDN3OHVvcUdTXG5qdzNuWkhNbUxuUzlieVk1QkFaU1V6YnpaQ0Q0NGlzNHdaTnpvclVDZ1lFQWxCU0drZmVtWVQwbFlmbGhCenV5XG5iQmwxNkh6bVVqUy91T2pKaVBDSGtCUFNlMndOZGVNaGJPZzdnZDdtSjY4NWhmMW9UdHpMTlBNb2NoeUpyTElEXG5nYWJHZEMwamdjM0dJbndvOGViR1N2U016UlM4Y0V6c01ab1hXSFhqVWN4Mi9TTTdYWUFZMWczQmozRncvbXBqXG4zbGdRYWc5eGV4VlBKZHZXeVpjcE5PZz1cbi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS1cbiIsCiAgImNsaWVudF9lbWFpbCI6ICIzNTg3MzM0MzYwNjEtY29tcHV0ZUBkZXZlbG9wZXIuZ3NlcnZpY2VhY2NvdW50LmNvbSIsCiAgImNsaWVudF9pZCI6ICIxMTU5NDE5MjkwMDc3MDQ3NjkyOTgiLAogICJhdXRoX3VyaSI6ICJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20vby9vYXV0aDIvYXV0aCIsCiAgInRva2VuX3VyaSI6ICJodHRwczovL29hdXRoMi5nb29nbGVhcGlzLmNvbS90b2tlbiIsCiAgImF1dGhfcHJvdmlkZXJfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9vYXV0aDIvdjEvY2VydHMiLAogICJjbGllbnRfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9yb2JvdC92MS9tZXRhZGF0YS94NTA5LzM1ODczMzQzNjA2MS1jb21wdXRlJTQwZGV2ZWxvcGVyLmdzZXJ2aWNlYWNjb3VudC5jb20iCn0=
    CLUSTER: dse
    ZONE: europe-west3-b
    PROJECT: maestermiddleware
    MIN_NODES: 1
    MAX_NODES: 3    
    IMAGE_USERNAME: dse-ss20-grp20
    APP_NAME_SVC1: actor-registry
    APP_FOLDER_SVC1: src/actor-registry

stages:
    - build
    - test
    - deploy

build-job:
    stage: build
    image: maven:3.6.0-jdk-11-slim
    script:
        - cd $APP_FOLDER_SVC1
        - mvn clean compile
    only:
        refs:
        - dev
        - master 

test-job:
    stage: test
    image: maven:3.6.0-jdk-11-slim
    script:
        - cd $APP_FOLDER_SVC1
        - mvn clean test
    only:
        refs:
        - dev
        - master


deploy-job:
    stage: deploy
    only:
    - master
    script:
        # Download Google Cloud SDK
        - wget https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz
        - tar zxvf google-cloud-sdk.tar.gz && ./google-cloud-sdk/install.sh --quiet --usage-reporting=false --path-update=true
        - PATH="google-cloud-sdk/bin:${PATH}"
        # Download kubectl
        - sudo apt-get update && sudo apt-get install -y apt-transport-https
        - curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
        - echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | tee -a /etc/apt/sources.list.d/kubernetes.list
        - apt-get update
        - apt-get install -y kubectl
        # Deploy to GCP
        - echo $GC_SERVICE_KEY | base64 -d > $HOME/key.json
        - gcloud config set project $PROJECT
        - gcloud auth activate-service-account --key-file $HOME/key.json
        - gcloud services enable container.googleapis.com
        - gcloud services enable cloudbuild.googleapis.com
        # gcloud container clusters create "$CLUSTER" --zone "$ZONE" --num-nodes=$MIN_NODES --enable-autoscaling --max-nodes=$MAX_NODES --min-nodes=$MIN_NODES
        - gcloud container clusters get-credentials "$CLUSTER" --zone "$ZONE"
        - gcloud auth configure-docker
        - gcloud builds submit $APP_FOLDER_SVC1 --tag gcr.io/$PROJECT/$IMAGE_USERNAME/$APP_NAME_SVC1
        # - cd $APP_FOLDER
        # - docker build . --tag $IMAGE_USERNAME/$APP_NAME
        # - docker push gcr.io/$PROJECT/$IMAGE_USERNAME/$APP_NAME
        - kubectl apply -f $APP_FOLDER_SVC1/deployment.yaml
        - kubectl apply -f $APP_FOLDER_SVC1/service.yaml
        # SVC2: - kubectl apply -f $APP_FOLDER_SVC2/deployment.yaml
        # SVC3: - kubectl apply -f $APP_FOLDER_SVC2/service.yaml       