variables:
    CLUSTER=dse
    ZONE=europe-west3-b
    PROJECT=maestermiddleware
    IMAGE_USERNAME=dse-ss20-grp20
    APP_NAME=actor-registry
    APP_FOLDER=container/actor-registry

services:
    - docker:dind

stages:
    - deploy

deploy-image:
    stage: deploy
    script:
        - echo $GC_SERVICE_KEY | base64 -d > $HOME/key.json
        - gcloud services enable container.googleapis.com
        # - gcloud container clusters create "$CLUSTER" --zone "$ZONE" --num-nodes=1--enable-autoscaling --max-nodes=5 --min-nodes=1
        - gcloud config set project $PROJECT
        - gcloud container clusters get-credentials "$CLUSTER" --zone "$ZONE"
        - gcloud auth configure-docker
        - cd $APP_FOLDER
        - docker build . --tag $IMAGE_USERNAME/$APP_NAME
        - docker push gcr.io/$PROJECT/$IMAGE_USERNAME/$APP_NAME
        - kubectl apply -f deployment.yaml
        - kubectl apply -f service.yaml