apiVersion: v1
kind: Service
metadata:
  name: actor-registry-service
  labels:
    app: actor-registry-service
spec:
  selector:
    app: actor-registry-service-deployment
    tier: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer