apiVersion: v1
kind: Service
metadata:
  name: actor-simulator-service
  labels:
    app: actor-simulator-service
spec:
  selector:
    app: actor-simulator-deployment
    tier: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
  externalIPs:
    #- 35.246.210.242