---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: status-tracking-deployment
    labels:
      app: status-tracking-deployment
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: status-tracking-deployment
    template:
      metadata:
        labels:
          app: status-tracking-deployment
          tier: web
      spec:
        containers:
          - name: status-tracking-container
            image: gcr.io/dse20-group-20/status-tracking
            ports:
              - containerPort: 8080